version: "3"
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel-project-php74
    restart: unless-stopped
    ports:
      - 8088:80
    volumes:
      - ./source:/var/www/html/